# Generated by Django 4.1.1 on 2023-04-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_headphones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headphones',
        ),
    ]
