# Generated by Django 4.1.1 on 2023-04-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_delete_headphones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('userpin', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('buying_date', models.DateField()),
                ('model_no', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('overall_condition', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='headphones/')),
                ('image2', models.ImageField(upload_to='headphones/')),
                ('image3', models.ImageField(upload_to='headphones/')),
            ],
        ),
    ]
