# Generated by Django 4.1.1 on 2023-04-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_remove_headphones_buying_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headphones',
        ),
    ]
