# Generated by Django 4.1.1 on 2023-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_headphones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('userpin', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('model_no', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('overall_condition', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='keyboards/')),
            ],
        ),
        migrations.CreateModel(
            name='laptops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('userpin', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('model_no', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('overall_condition', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='laptops/')),
            ],
        ),
        migrations.CreateModel(
            name='mouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('userpin', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('model_no', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('overall_condition', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='mouse/')),
            ],
        ),
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('userpin', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('model_no', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('overall_condition', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='phones/')),
            ],
        ),
        migrations.CreateModel(
            name='speakers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('userpin', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('model_no', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('overall_condition', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='speakers/')),
            ],
        ),
        migrations.CreateModel(
            name='tvs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('userpin', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('model_no', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('overall_condition', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='tvs/')),
            ],
        ),
        migrations.CreateModel(
            name='watches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('userpin', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('model_no', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('overall_condition', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='watches/')),
            ],
        ),
    ]
