# Generated by Django 4.1.1 on 2023-04-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_keyboards_laptops_mouse_phones_speakers_tvs_watches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headphones',
        ),
        migrations.DeleteModel(
            name='Keyboards',
        ),
        migrations.DeleteModel(
            name='laptops',
        ),
        migrations.DeleteModel(
            name='mouse',
        ),
        migrations.DeleteModel(
            name='phones',
        ),
        migrations.DeleteModel(
            name='speakers',
        ),
        migrations.DeleteModel(
            name='tvs',
        ),
        migrations.DeleteModel(
            name='watches',
        ),
    ]
