# Generated by Django 4.1.1 on 2023-05-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_vendorstocks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorStocks',
        ),
    ]
